version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tedious
    versions:
    - 11.0.1
    - 11.0.3
    - 11.0.4
    - 11.0.5
    - 11.0.6
